name: Continuous Integration

on:    
  workflow_dispatch:

jobs:    
  build-package:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}           
            
      - name: Publish New Repo Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo Creating Repo Release
          gh release create v${{steps.semantic.outputs.new_release_version}} -t "Release ${{steps.semantic.outputs.new_release_version}}" -F CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}